### ISSUE TITLE
Would like to set the expand/collapse icons

### ISSUE THREAD

**Issue by rsivan** [vaadin/vaadin-details#10]
My UIX team asks that we use a pattern similar to this: https://material.angular.io/components/expansion/overview.
Can you please provide customizable icons for expand and collapse?
Thanks

**Comment by web-padawan** [comment]
Just to clarify, are you using the material theme? If so, the icon is specified here:

https://github.com/vaadin/vaadin-details/blob/b4a5d5380ce7500de4514b5c92728f29e31d1039/theme/material/vaadin-details-styles.html#L62-L68

You can add a `dom-module` to use another icon like this:
```html
<dom-module id="custom-details" theme-for="vaadin-details">
  <template>
    <style>
      [part="toggle"]::before {
        font-family: "Font Awesome 5 Free";
        content:  "\f077"; /* chevron-up */
      }
    </style>
  </template>
</dom-module>
```

**Comment by rsivan** [comment]
I tried overriding the current dom-module as follows:
`            :host([opened]) [part="toggle"] {
                transform: rotate(270deg);
            }`

`            :host [part="toggle"] {
                transform: rotate(90deg);
`
However is looks like CSS overrides that with the library definition...
Any thoughts on this?

Thanks

**Comment by rsivan** [comment]
Actually my question should rather be: how to apply a new theme variant from Vaadin-Flow? Do I need to subclass "Details"?

**Comment by web-padawan** [comment]
I'm sorry that we left this without an answer for a while.

With Vaadin 14, there is a `CssImport` Java API for that:

```
@CssImport(value = "./styles/my-detials-styles.css", themeFor = "vaadin-details");
```

There are some examples for other components in the docs:
https://vaadin.com/docs/v14/flow/theme/tutorial-theming-overlay.html

I'm closing this issue as the problem can be solved with existing API.
