### ISSUE TITLE
Lots of content in the summary overflows/breaks the layout

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-details#3]

**Comment by web-padawan** [comment]
One option would be to remove fixed height in Lumo:
https://github.com/vaadin/vaadin-details/blob/75165f1510e4d9394f5d874ca3c22009650a787b/theme/lumo/vaadin-details-styles.html#L23
And align it with Material which already does that:
https://github.com/vaadin/vaadin-details/blob/75165f1510e4d9394f5d874ca3c22009650a787b/theme/material/vaadin-details-styles.html#L22

There could be a theme to have `white-space: nowrap` and `overflow: ellipsis`, like `theme="nowrap"` (we have this kind of theme for the Grid but it to wrap cell content).

@jouni WDYT?

**Comment by jouni** [comment]
Yeah, would prefer to use `min-height` instead of a fixed height. Note, that row flex centering and min-height do not work together in IE11.
