### ISSUE TITLE
Broken <vaadin-details> in production mode

### ISSUE THREAD

**Issue by moryakovdv** [vaadin/vaadin-details#36]
Hello.
Probably a bug in Vaadin 14.3.4 + SpringBoot
When I am in debug mode the ```<vaadin-details>``` works as expected (see attachment-1)
After building with Maven 'production' profile ```<vaadin-details>``` lose it's styles and stays completely expanded (attachment-2)
Here is a code of PolymerElement. Is is almost the same as in Vaadin samples
```import { PolymerElement } from '@polymer/polymer/polymer-element.js';
import { html } from '@polymer/polymer/lib/utils/html-tag.js';
import '@vaadin/vaadin-form-layout/vaadin-form-layout.js';
import '@vaadin/vaadin-form-layout/vaadin-form-item.js';
import '@vaadin/vaadin-text-field/vaadin-text-field.js';
import '@vaadin/vaadin-text-field/vaadin-text-area.js';
import '@vaadin/vaadin-button/vaadin-button.js';
import '@vaadin/vaadin-ordered-layout/vaadin-horizontal-layout.js';
import '@vaadin/vaadin-ordered-layout/vaadin-vertical-layout.js';`
import { PolymerElement } from '@polymer/polymer/polymer-element.js';
import { html } from '@polymer/polymer/lib/utils/html-tag.js';
import '@vaadin/vaadin-form-layout/vaadin-form-layout.js';
import '@vaadin/vaadin-form-layout/vaadin-form-item.js';
import '@vaadin/vaadin-text-field/vaadin-text-field.js';
import '@vaadin/vaadin-text-field/vaadin-text-area.js';
import '@vaadin/vaadin-button/vaadin-button.js';
import '@vaadin/vaadin-ordered-layout/vaadin-horizontal-layout.js';
import '@vaadin/vaadin-ordered-layout/vaadin-vertical-layout.js';
```
```class UsersettingsView extends PolymerElement {
  static get template() {
    return html`
      <custom-style>
        <style include="shared-styles lumo-typography">
          .button-layout {
            display: flex;
            flex-wrap: wrap-reverse;
            width: 100%;
            justify-content: flex-end;
          }
        </style>
      </custom-style>   
      <vaadin-details>
      		<div slot="summary">detail</div>
      		<h1>DETAILS</h1>
      </vaadin-details>
      <vaadin-vertical-layout id="wrapper">
        <h1>Form</h1>
        <vaadin-form-layout class="test2">
          <vaadin-form-item>
            <label slot="label">First name</label>
            <vaadin-text-field id="firstName" class="full-width" value=""></vaadin-text-field>
          </vaadin-form-item>
          <vaadin-form-item>
            <label slot="label">Last name</label>
            <vaadin-text-field id="lastName" class="full-width" value=""></vaadin-text-field>
          </vaadin-form-item>
          <vaadin-form-item >
            <label slot="label">Email</label>
            <vaadin-text-field id="email" class="full-width" value=""></vaadin-text-field>
          </vaadin-form-item>
        </vaadin-form-layout>
        <vaadin-horizontal-layout
          theme="spacing"
          style="display:flex;flex-wrap:wrap-reverse;width:100%;justify-content:flex-end;"
        >
          <vaadin-button theme="tertiary" id="cancel" slot="">
            Cancel
          </vaadin-button>
          <vaadin-button theme="primary" id="save">
            Save
          </vaadin-button>
        </vaadin-horizontal-layout>
      </vaadin-vertical-layout>
    `;
  }
  static get is() {
    return 'usersettings-view';
  }
  static get properties() {
    return {
      // Declare your properties here.
    };
   
  }
 
}

customElements.define(UsersettingsView.is, UsersettingsView);`
```

![image](https://user-images.githubusercontent.com/14349345/96254994-debc0900-0fbe-11eb-8640-42d7dc2b5ff9.png)
![image](https://user-images.githubusercontent.com/14349345/96255024-ebd8f800-0fbe-11eb-80bd-23c7845f7889.png)

**Comment by moryakovdv** [comment]
UPD: I found a workaround. 
Just add Details component creation somewhere in the java code. You don't need to attach this object to any layout or set any properties to it. Just instantiate.
```
private Details details = new Details();
public MainView() {
}
```
After that all `<vaadin-details>` work as expected whether they were created in java-side or js-side.

Hope this will help to find the main reason of the issue.

**Comment by web-padawan** [comment]
Thanks for the issue. Please note that your original code snippet is missing the import for the component:

```js
import '@vaadin/vaadin-details/vaadin-details.js';
```

Did you try to add it and see if that helps? I'm pretty sure that's the reason of the problem that you have.

What happens in practice is that in development mode Vaadin creates a bundle with all the components. But in production mode, only the actually used components are included to the bundle and that requires an explicit import.

**Comment by moryakovdv** [comment]
Hello,
You are right, it works.
Adding ```import '@vaadin/vaadin-details/vaadin-details.js';```  solves the problem.
Pretty sure this should be mentioned somewhere in docs, but I can't find it neither 
[there](https://vaadin.com/docs/flow/production/tutorial-production-mode-basic.html) or
[there](https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-advanced.html)
Or may be some of "dealing with polymer" tutorials are the right place.
Anyway, thanks a lot.
Closed.

**Comment by web-padawan** [comment]
Thanks for your feedback ! I will create an issue to update the docs as you suggested.
