### ISSUE TITLE
Any inside heading click allows to collapse/expand details

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-details#4]
When the component disabled, some clicks made on summary expands or collapses details.

Basically, only click on `div role="heading"` works as expected. Everything inside of it behaves as enabled component.

Not sure if it's a bug or feature

**Comment by web-padawan** [comment]
Note: as discussed in person, this happens for synthetic click, e.g. invoking `click()` method manually on the slotted button.

**Comment by alexberazouski** [comment]
Exactly, but I checked it again, and it happens not only for slotted content, but for any part inside of the heading. So I cannot simulate toggle in Testbench API which won't work with disabled component

**Comment by web-padawan** [comment]
This will be covered with migrating to LitElement especially by https://github.com/vaadin/vaadin-details/pull/15/commits/b618c067e6c2260e08c8173821173167d3fe8d7c

**Comment by web-padawan** [comment]
Fixed by #15. 

As long as it is only valid for synthetic clicks and no one has complaint, I don't consider it a bug.
